# Dockerfile template. ${TAG} and ${REGISTRY} needs to be set.
FROM muccg/python-base:ubuntu14.04-2.7
MAINTAINER https://bitbucket.org/ccgmurdoch/disease_registry/

ENV DEBIAN_FRONTEND noninteractive

# Project specific deps
RUN apt-get update && apt-get install -y --no-install-recommends \
  libpcre3 \
  libpcre3-dev \
  libpq-dev \
  libssl-dev \
  libxml2-dev \
  libxslt1-dev \
  libssl-dev \
  libsasl2-dev \
  libyaml-dev \
  wget \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN env --unset=DEBIAN_FRONTEND

# install python deps
WORKDIR /app
RUN echo TAG \
    && wget https://bitbucket.org/ccgmurdoch/disease_registry/get/TAG.tar.gz \
    && tar zxvf TAG.tar.gz --strip 1 \
    && ls -la

RUN cp docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

RUN pip install --process-dependency-links -e REGISTRY

EXPOSE 9100 9101
VOLUME ["/data"]

# Drop privileges, set home for ccg-user
USER ccg-user
ENV HOME /data
ENV APP REGISTRY
WORKDIR /data

# entrypoint shell script that by default starts runserver
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["uwsgi"]
